from collections.abc import Mapping, Sequence
from typing import Any
import logging
from time import perf_counter

from langchain_core.messages import ToolMessage
from langchain_core.tools import BaseTool
from langgraph.graph import END, START, StateGraph

from app.ai.workflows.graph_state import GraphState
from app.ai.prompt_builders.state_summary_builder import StateSummaryBuilder
from app.domain.exceptions.workflow_error import WorkflowError
from app.domain.models.execution_context import ExecutionContext

logger = logging.getLogger(__name__)


class PresentationGraph:
    """
    LangGraph workflow orchestrating the Healthcare Presentation Assistant.
    """

    def __init__(
        self,
        agent: Any,
        tools: Sequence[BaseTool] | Mapping[str, BaseTool],
    ) -> None:
        self.builder = StateGraph(GraphState)
        self.agent = agent
        self.state_summary_builder = StateSummaryBuilder()
        self.tools = (
            dict(tools)
            if isinstance(tools, Mapping)
            else {tool.name: tool for tool in tools}
        )
        self._register_nodes()
        self._register_edges()

    def _register_nodes(self) -> None:
        self.builder.add_node("agent", self._agent_node)
        self.builder.add_node("tool", self._tool_node)

    def _register_edges(self) -> None:
        self.builder.add_edge(START, "agent")
        self.builder.add_conditional_edges(
            "agent",
            self._should_continue,
            {"tool": "tool", "end": END},
        )
        self.builder.add_edge("tool", "agent")

    def _agent_node(self, state: GraphState) -> dict[str, list]:
        response = self.agent.invoke(
            {
                "messages": state.messages,
                "state_summary": self.state_summary_builder.build(state),
            }
        )
        return {"messages": [response]}

    def _tool_node(self, state: GraphState) -> dict[str, Any]:
        last_message = state.messages[-1]
        tool_calls = getattr(last_message, "tool_calls", None)

        if not tool_calls:
            return {}

        tool_messages = []
        last_tool = None
        error: WorkflowError | None = None
        current_state = state

        for position, tool_call in enumerate(tool_calls):
            tool_name = tool_call["name"]
            if position == 0:
                last_tool = tool_name
            tool = self.tools.get(tool_name)
            allowed_tools = self.state_summary_builder.allowed_tools(current_state)

            if position > 0:
                error = WorkflowError(
                    "ONE_ACTION_PER_TURN",
                    "Only one workflow action can be executed at a time.",
                )
                content = f"TOOL_BLOCKED {error.code}: {error.user_message}"
            elif tool is None:
                error = WorkflowError("UNKNOWN_TOOL", "The requested workflow action is unavailable.")
                content = f"TOOL_BLOCKED {error.code}: {error.user_message}"
            elif tool_name not in allowed_tools:
                error = WorkflowError(
                    "WORKFLOW_ACTION_NOT_ALLOWED",
                    "This action is not available at the current workflow stage.",
                )
                content = f"TOOL_BLOCKED {error.code}: {error.user_message}"
            else:
                try:
                    started_at = perf_counter()
                    # GraphState is injected by the graph, never generated by the LLM.
                    result = tool.func(current_state, **tool_call.get("args", {}))
                    if isinstance(result, GraphState):
                        current_state = result
                    content = f"{tool_name} completed."
                    logger.info(
                        "tool_completed tool=%s duration_ms=%.2f has_presentation=%s",
                        tool_name,
                        (perf_counter() - started_at) * 1000,
                        current_state.presentation is not None,
                    )
                except WorkflowError as exc:
                    error = exc
                    content = f"TOOL_BLOCKED {error.code}: {error.user_message}"
                    logger.info("tool_blocked tool=%s code=%s", tool_name, error.code)
                except ValueError as exc:
                    error = WorkflowError("WORKFLOW_VALIDATION_FAILED", str(exc))
                    content = f"TOOL_BLOCKED {error.code}: {error.user_message}"
                    logger.info("tool_validation_failed tool=%s error=%s", tool_name, exc)
                except Exception as exc:
                    error = WorkflowError(
                        "WORKFLOW_EXECUTION_FAILED",
                        "The workflow action could not be completed. Please retry.",
                        retryable=True,
                    )
                    content = f"TOOL_FAILED {error.code}: {error.user_message}"
                    logger.exception("tool_failed tool=%s", tool_name)

            tool_messages.append(
                ToolMessage(
                    content=content,
                    tool_call_id=tool_call["id"],
                    name=tool_name,
                )
            )

        return {
            "messages": tool_messages,
            "conversation_context": current_state.conversation_context,
            "presentation_context": current_state.presentation_context,
            "presentation": current_state.presentation,
            "execution": ExecutionContext(
                last_tool=last_tool,
                tool_output={
                    "status": "error" if error else "ok",
                    "tool": last_tool,
                    "error_code": error.code if error else None,
                    "retryable": error.retryable if error else False,
                },
                error=error.user_message if error else None,
            ),
        }

    def _should_continue(self, state: GraphState) -> str:
        last_message = state.messages[-1]

        if getattr(last_message, "tool_calls", None):
            return "tool"

        return "end"

    def compile(self):
        return self.builder.compile()
