from typing import Literal

from pydantic import BaseModel, Field


ContentOrigin = Literal["ai_generated", "user_edited", "user_authored"]


class SlideOutline(BaseModel):
    """
    Represents a planned slide before
    its content is generated.
    """

    slide_number: int = Field(
        ...,
        ge=1,
        description="Slide order in the presentation.",
    )

    title: str = Field(
        ...,
        description="Slide title.",
    )

    objective: str = Field(
        ...,
        description="Learning objective of the slide.",
    )

    key_message: str = Field(
        ...,
        description="Main message the audience should remember.",
    )

    is_validated: bool = Field(default=False)

    reviewer_comments: str | None = Field(default=None)

    content_origin: ContentOrigin = Field(
        default="ai_generated",
        description="Whether this outline was generated by the model or written/edited by the user.",
    )

    original_ai_snapshot: dict[str, object] | None = Field(
        default=None,
        description="Immutable-in-practice snapshot retained when a user first edits AI content.",
    )
