from typing import List, Literal, Optional

import hashlib
import json

from pydantic import BaseModel, Field, model_validator

from app.domain.models.claim_evidence import EvidenceLink, LegacySlideReference, MedicalClaim
from app.domain.value_objects.speaker_note import SpeakerNote


class Slide(BaseModel):
    """
    Represents a single slide of a healthcare presentation.
    """

    slide_number: int = Field(
        ...,
        gt=0,
        description="Slide position in the presentation.",
    )

    title: str = Field(
        ...,
        description="Slide title.",
    )

    objective: Optional[str] = Field(
        default=None,
        description="Learning objective of the slide.",
    )

    key_messages: List[str] = Field(
        default_factory=list,
        description="Main messages to communicate.",
    )

    content: str = Field(
        default="",
        description="Generated slide content.",
    )

    speaker_notes: Optional[str] = Field(
        default=None,
        description="Speaker notes associated with the slide.",
    )

    speaker_note: SpeakerNote | None = Field(
        default=None,
        description="Speaker notes and their evidence, separate from visible slide content.",
    )

    references: List[str] = Field(
        default_factory=list,
        description="Scientific references supporting the slide.",
    )

    reference_details: List[dict[str, object]] = Field(
        default_factory=list,
        description="Evidence provenance: resource ID, page, excerpt and bibliographic reference.",
    )

    claims: List[MedicalClaim] = Field(default_factory=list)

    evidence_links: List[EvidenceLink] = Field(default_factory=list)

    legacy_references: List[LegacySlideReference] = Field(default_factory=list)

    evidence_verified: bool = Field(
        default=False,
        description="Whether every citation was verified against an uploaded PDF page.",
    )

    visual_recommendations: List[str] = Field(
        default_factory=list,
        description="Suggested visuals for this slide.",
    )

    is_validated: bool = Field(
        default=False,
        description="Whether the slide has been validated by the user.",
    )

    reviewer_comments: str | None = Field(
        default=None,
        description="Human reviewer comments for this slide.",
    )

    content_origin: Literal["ai_generated", "user_edited", "user_authored"] = Field(
        default="ai_generated",
        description="Whether this slide was generated by the model or written/edited by the user.",
    )

    original_ai_snapshot: dict[str, object] | None = Field(
        default=None,
        description="Original model content retained when a user first edits an AI slide.",
    )

    evidence_review_required: bool = Field(
        default=False,
        description="True when manual content changes mean evidence can no longer be attributed to the model output.",
    )
    @model_validator(mode="before")
    @classmethod
    def migrate_legacy_references(cls, value):
        """Keep old slide citations losslessly, idempotently and unassigned.

        A slide-level reference cannot be attributed to every claim.  Migration
        therefore creates review items only; it grants no semantic approval.
        """
        if (not isinstance(value, dict) or value.get("legacy_references")
                or value.get("claims") or value.get("evidence_links")):
            return value
        references = value.get("reference_details")
        if not isinstance(references, list) or not references:
            return value
        migrated = dict(value)
        legacy = []
        for reference in references:
            if not isinstance(reference, dict):
                continue
            canonical = json.dumps(reference, sort_keys=True, separators=(",", ":"), default=str)
            legacy.append({
                "migration_id": f"legacy-{hashlib.sha256(canonical.encode()).hexdigest()[:20]}",
                "reference": reference,
                "review_required": True,
            })
        migrated["legacy_references"] = legacy
        migrated["evidence_review_required"] = True
        migrated["evidence_verified"] = False
        return migrated
