from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class Slide(BaseModel):
    """
    Represents a single slide of a healthcare presentation.
    """

    slide_number: int = Field(
        ...,
        gt=0,
        description="Slide position in the presentation.",
    )

    title: str = Field(
        ...,
        description="Slide title.",
    )

    objective: Optional[str] = Field(
        default=None,
        description="Learning objective of the slide.",
    )

    key_messages: List[str] = Field(
        default_factory=list,
        description="Main messages to communicate.",
    )

    content: str = Field(
        default="",
        description="Generated slide content.",
    )

    speaker_notes: Optional[str] = Field(
        default=None,
        description="Speaker notes associated with the slide.",
    )

    references: List[str] = Field(
        default_factory=list,
        description="Scientific references supporting the slide.",
    )

    reference_details: List[dict[str, object]] = Field(
        default_factory=list,
        description="Evidence provenance: resource ID, page, excerpt and bibliographic reference.",
    )

    evidence_verified: bool = Field(
        default=False,
        description="Whether every citation was verified against an uploaded PDF page.",
    )

    visual_recommendations: List[str] = Field(
        default_factory=list,
        description="Suggested visuals for this slide.",
    )

    is_validated: bool = Field(
        default=False,
        description="Whether the slide has been validated by the user.",
    )

    reviewer_comments: str | None = Field(
        default=None,
        description="Human reviewer comments for this slide.",
    )

    content_origin: Literal["ai_generated", "user_edited", "user_authored"] = Field(
        default="ai_generated",
        description="Whether this slide was generated by the model or written/edited by the user.",
    )

    original_ai_snapshot: dict[str, object] | None = Field(
        default=None,
        description="Original model content retained when a user first edits an AI slide.",
    )

    evidence_review_required: bool = Field(
        default=False,
        description="True when manual content changes mean evidence can no longer be attributed to the model output.",
    )
